# Generated by Django 5.1.1 on 2024-09-23 20:21

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите видео",
                null=True,
                validators=[courses.validators.validate_youtube_link],
                verbose_name="Видео",
            ),
        ),
    ]
